version: '3.8'

networks:
  netw:
    driver: bridge

services:
  mongodatabase:
    image: mongo:latest
    container_name: mongodatabase
    volumes:
      - ./data:/dumbdata
    restart: on-failure:3
    environment:
      MONGO_INITDB_ROOT_USERNAME: lappis
      MONGO_INITDB_ROOT_PASSWORD: l4pp1s
      MONGO_INITDB_DATABASE: metabase
    ports:
      - "27017:27017"
    networks:
    - netw

  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: lappis
      MB_DB_PASS: l4pp1s
      MB_DB_HOST: postgres
    depends_on:
      - postgres
      - mongodatabase
    volumes:
      - ./metabase:/metabase-data
    networks:
    - netw

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: lappis
      POSTGRES_PASSWORD: l4pp1s
      POSTGRES_DB: metabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
    - netw

  app:
    container_name: app
    restart: on-failure:3
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/src
    command: python main.py
    volumes:
      - ./:/app
    depends_on:
      - mongodatabase
    ports:
      - "5000:5000"
    networks:
      - netw

volumes:
  pgdata: