name: CD

on:
  release:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Publish With Poetry
        uses: celsiusnarhwal/poetry-publish@v2.0.2
        with:
          python-version: 3.8
          poetry-version: 1.3.2
          token: ${{ secrets.PYPI_TOKEN }}
          build: true

