name: CD

on:
  release:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v8
      - name: Install Poetry and Build Package
        run: |
          cd gces-bib
          poetry version major
          poetry build
          poetry install
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish

