
name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Gr1N/setup-poetry@v8
      - uses: actions/checkout@v1
      - name: Setup Poetry
        run: |
          cd gces-bib
          poetry build
        
